name: Build zips

on:
  push:
    branches: [ enable-deploy-to-aws ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Make artifact directory
      run: mkdir -p './artifacts'

    - name: Create Zip File
      run: ls
      # uses: montudor/action-zip@v0.1.0
      # with:
      #   args: zip -r ./artifacts/code.zip ./services/sample-service/functions/sample

    - name: Push Zip to S3
      uses: jakejarvis/s3-sync-action@v0.3.1
      env:
        SOURCE_DIR: './artifacts'
        AWS_REGION: 'us-east-1'
        AWS_S3_BUCKET: 'us-east-1'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}