name: Build zips

on:
  push:
    branches: [ enable-deploy-to-aws ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
    # - name: Make artifact directory
    #   run: |
    #     mkdir -p './artifacts'

      - name: Create Zip File
        run: |
          cd ..
          cd ..
          cd ..
          cd ..
          cd ./runner/work
          mkdir -p './artifacts'
          tree -f
          zip -r ./artifacts/output_file.zip ./diggy/services/sample-service/functions/sample

      - name: Push Zip to S3
        uses: jakejarvis/s3-sync-action@v0.3.1
        env:
          SOURCE_DIR: './artifacts'
          AWS_REGION: 'us-east-1'
          AWS_S3_BUCKET: 'us-east-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}